baseurl = "https://www.itsnothing.de/"
languageCode = "en-US"
theme = "terminal"
paginate = 3
publishDir = "docs"

[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "It's Nothing"
    subtitle = "Ekkis Blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "It's Nothing"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "portfolio"
        name = "Portfolio"
        url = "/portfolio"
        weight = "80"
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://www.twitter.com/ekkiiiii"
        weight = "100"
      [[languages.en.menu.main]]
        identifier = "Letterboxd"
        name = "Letterboxd"
        url = "https://letterboxd.com/ekkiiiii/"
        weight = "100"
      [[languages.en.menu.main]]
        identifier = "about-me"
        name = "About Me"
        url = "/about-me"
        weight = "90"
      [[languages.en.menu.about]]
        identifier = "about-this-site"
        name = "About this site"
        url = "/about-this-site"
        weight = "90"
